// Auto-generated by scripts/fetchDemoUsers.ts
export interface DemoUser {
    email: string;
    role: string;
    label?: string; // Derived label
}

export const DEMO_USERS: DemoUser[] = [
    {
        "email": "admin@spendigo.ca",
        "role": "admin",
        "label": "ADMIN"
    },
    {
        "email": "admin2@spendigo.ca",
        "role": "admin",
        "label": "ADMIN"
    },
    {
        "email": "al_shahb@outlook.com",
        "role": "merchant",
        "label": "MERCH"
    },
    {
        "email": "bakery.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "bakery.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "bakery.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "bodega.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "bodega.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "bodega.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "books.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "books.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "books.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "butcher.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "butcher.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "butcher.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "cornerbodega.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "cornerbodega.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "cornerbodega.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "costco.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "costco.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "costco.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "costcobusiness.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "costcobusiness.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "costcobusiness.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "freshmart.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "freshmart.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "freshmart.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "greenvalley.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "greenvalley.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "greenvalley.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "greenvalleymarket.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "greenvalleymarket.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "greenvalleymarket.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "hasty.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "hasty.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "hasty.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "hastymart.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "hastymart.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "hastymart.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "macs.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "macs.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "macs.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "macscorner.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "macscorner.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "macscorner.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "metro.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "metro.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "metro.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "metroexpress.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "metroexpress.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "metroexpress.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "quickpick.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "quickpick.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "quickpick.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "thebooknook.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "thebooknook.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "thebooknook.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "thebutchersblock.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "thebutchersblock.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "thebutchersblock.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "thedailyloaf.manager@spendigo.ca",
        "role": "merchant",
        "label": "MNGR"
    },
    {
        "email": "thedailyloaf.owner@spendigo.ca",
        "role": "merchant",
        "label": "OWNER"
    },
    {
        "email": "thedailyloaf.staff@spendigo.ca",
        "role": "merchant",
        "label": "STAFF"
    },
    {
        "email": "verif_merch@test.com",
        "role": "merchant",
        "label": "MERCH"
    },
    {
        "email": "verif_merchant@test.com",
        "role": "merchant",
        "label": "MERCH"
    },
    {
        "email": "al_sb@outpacexct.com",
        "role": "consumer",
        "label": "USER"
    },
    {
        "email": "chef@spendigo.ca",
        "role": "consumer",
        "label": "USER"
    },
    {
        "email": "family@spendigo.ca",
        "role": "consumer",
        "label": "USER"
    },
    {
        "email": "shopper@example.com",
        "role": "consumer",
        "label": "USER"
    },
    {
        "email": "student@spendigo.ca",
        "role": "consumer",
        "label": "USER"
    },
    {
        "email": "sync_check_9977@test.com",
        "role": "consumer",
        "label": "USER"
    },
    {
        "email": "verif_shopper@test.com",
        "role": "consumer",
        "label": "USER"
    },
    {
        "email": "verif_user@test.com",
        "role": "consumer",
        "label": "USER"
    }
];
